export const sunoPrompts = [
  // Pop
  {
    id: 'pop',
    category: 'pop',
    title: 'Pop（流行）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Upbeat pop, catchy melody, synth pop, 120 BPM, Key of C major, radio-friendly, modern production, harmonic chorus`,
  },
  {
    id: 'indie-pop',
    category: 'pop',
    title: 'Indie Pop（独立流行）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Indie pop, dreamy synths, jangly guitar, soft vocals, 105 BPM, intimate production, bittersweet, warm`,
  },
  {
    id: 'k-pop',
    category: 'pop',
    title: 'K-Pop',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `K-pop, girl group, electronic, auto-tune vocals, dance beat, bright synth, 130 BPM, Korean lyrics`,
  },
  {
    id: 'j-pop',
    category: 'pop',
    title: 'J-Pop',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `J-pop, anime style, upbeat, piano-driven, cheerful, Japanese lyrics, catchy chorus`,
  },
  {
    id: 'synth-pop',
    category: 'pop',
    title: 'Synth Pop（合成器流行）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Synth pop, 80s inspired, analog synths, drum machine, bright melody, 118 BPM, retro-futuristic, polished`,
  },
  {
    id: 'bedroom-pop',
    category: 'pop',
    title: 'Bedroom Pop（卧室流行）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Bedroom pop, lo-fi production, soft vocals, guitar and synth, 100 BPM, hazy, personal, intimate recording`,
  },

  // R&B / Soul
  {
    id: 'rnb',
    category: 'rnb-soul',
    title: 'R&B（R&B / Soul）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Smooth R&B, slow groove, 85 BPM, Key of E minor, soulful vocals, piano, warm bass, bedroom vibes`,
  },
  {
    id: 'neo-soul',
    category: 'rnb-soul',
    title: 'Neo-Soul（新灵魂乐）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Neo-soul, laid-back, jazzy chords, 90 BPM, Key of G major, organic instrumentation, soulful, vintage feel`,
  },
  {
    id: 'contemporary-rnb',
    category: 'rnb-soul',
    title: 'Contemporary R&B（当代 R&B）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Contemporary R&B, atmospheric, 808 bass, ambient pads, falsetto vocals, 78 BPM, moody, dark production`,
  },

  // Rock
  {
    id: 'classic-rock',
    category: 'rock',
    title: 'Classic Rock（经典摇滚）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Classic rock, electric guitar, driving drums, 120 BPM, Key of A major, raw energy, anthemic chorus`,
  },
  {
    id: 'indie-rock',
    category: 'rock',
    title: 'Indie Rock（独立摇滚）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Indie rock, jangly guitar, earnest vocals, 110 BPM, dreamy, reverb-heavy, alternative`,
  },
  {
    id: 'metal',
    category: 'rock',
    title: 'Metal（金属）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Heavy metal, distorted guitars, double bass drums, aggressive, 180 BPM, dark, Key of D minor`,
  },
  {
    id: 'punk-rock',
    category: 'rock',
    title: 'Punk Rock（朋克摇滚）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Punk rock, fast tempo, distorted guitar, raw vocals, 160 BPM, rebellious, stripped-down production, energetic`,
  },
  {
    id: 'grunge',
    category: 'rock',
    title: 'Grunge（垃圾摇滚）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Grunge, heavy distorted guitar, angsty vocals, 110 BPM, 90s Seattle sound, raw, dynamic soft-loud contrast`,
  },
  {
    id: 'post-rock',
    category: 'rock',
    title: 'Post-Rock（后摇）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Post-rock, atmospheric guitar layers, crescendo builds, no vocals, instrumental, reverb-heavy, cinematic, 90 BPM`,
  },
  {
    id: 'shoegaze',
    category: 'rock',
    title: 'Shoegaze（自赏派）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Shoegaze, wall of distorted guitar, dreamy buried vocals, heavy reverb, ethereal, 95 BPM, hazy, layered textures`,
  },

  // Electronic
  {
    id: 'lo-fi',
    category: 'electronic',
    title: 'Lo-fi（慵懒电子）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Lo-fi hip hop, chill beats, vinyl crackle, 80 BPM, dusty samples, piano, relaxed`,
  },
  {
    id: 'edm-house',
    category: 'electronic',
    title: 'EDM / House',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `EDM, big room house, drop, festival anthem, four-on-the-floor beat, 128 BPM, euphoric, build-up`,
  },
  {
    id: 'deep-house',
    category: 'electronic',
    title: 'Deep House',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Deep house, groovy bassline, warm pads, 122 BPM, late-night atmosphere, smooth, subtle vocals, hypnotic`,
  },
  {
    id: 'techno',
    category: 'electronic',
    title: 'Techno',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Techno, driving beat, dark atmosphere, 130 BPM, industrial, hypnotic loops, minimal, underground club`,
  },
  {
    id: 'ambient',
    category: 'electronic',
    title: 'Ambient（氛围）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Ambient electronic, atmospheric, spacious, 60 BPM, synth pads, slowly evolving, meditative`,
  },
  {
    id: 'drum-and-bass',
    category: 'electronic',
    title: 'Drum & Bass',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Drum and bass, fast breakbeats, heavy sub-bass, 174 BPM, energetic, rolling drums, dark atmosphere`,
  },
  {
    id: 'synthwave-retrowave',
    category: 'electronic',
    title: 'Synthwave / Retrowave',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Synthwave, 80s retro electronic, neon atmosphere, pulsing bass, arpeggiated synths, 110 BPM, cinematic`,
  },
  {
    id: 'chillwave',
    category: 'electronic',
    title: 'Chillwave',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Chillwave, hazy synths, lo-fi texture, dreamy vocals, nostalgic, sun-drenched, 95 BPM, washed out`,
  },

  // Jazz
  {
    id: 'smooth-jazz',
    category: 'jazz',
    title: 'Smooth Jazz',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Smooth jazz, mellow saxophone, electric piano, soft drums, easy listening, warm, relaxed, wine bar atmosphere`,
  },
  {
    id: 'bebop',
    category: 'jazz',
    title: 'Bebop',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Bebop jazz, fast tempo, complex chord changes, saxophone lead, walking bass, ride cymbal, 1940s style, virtuosic`,
  },
  {
    id: 'bossa-nova',
    category: 'jazz',
    title: 'Bossa Nova',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Bossa nova, nylon guitar, soft percussion, gentle vocals, Brazilian jazz, 120 BPM, warm, romantic, laid-back`,
  },
  {
    id: 'jazz-fusion',
    category: 'jazz',
    title: 'Jazz Fusion（爵士融合）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Jazz fusion, electric instruments, rock energy, complex arrangements, 70s sophistication, funky, syncopated, 130 BPM`,
  },

  // Classical
  {
    id: 'piano-solo',
    category: 'classical',
    title: 'Piano Solo（钢琴独奏）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Piano solo, classical influence, romantic era, adagio tempo, emotional, expressive, Key of F minor`,
  },
  {
    id: 'chamber-music',
    category: 'classical',
    title: 'Chamber Music（室内乐）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Chamber ensemble, string quartet, elegant, Baroque style, delicate, intricate harmonies`,
  },
  {
    id: 'cinematic-film-score',
    category: 'classical',
    title: 'Cinematic / Film Score（影视配乐）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Cinematic orchestral, epic strings, brass fanfare, timpani, heroic, sweeping melody, film soundtrack, grand`,
  },
  {
    id: 'neoclassical',
    category: 'classical',
    title: 'Neoclassical（新古典）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Neoclassical, modern classical, piano and strings, minimal, emotional, Nils Frahm style, contemplative, spacious`,
  },

  // World Music
  {
    id: 'chinese-traditional',
    category: 'world',
    title: 'Chinese Traditional（中国传统）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Chinese traditional, guzheng, bamboo flute (dizi), peaceful, nature sounds, classical Chinese mood`,
  },
  {
    id: 'chinese-orchestral',
    category: 'world',
    title: 'Chinese Orchestral（国风交响）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Chinese orchestral, erhu melody, pipa arpeggios, guzheng, pentatonic scale, grand, emotional, traditional Chinese instruments with orchestral strings`,
  },
  {
    id: 'chinese-pop',
    category: 'world',
    title: 'Chinese Pop / 华语流行',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `C-pop ballad, emotional piano, string section, Mandarin lyrics, tender vocals, 75 BPM, heartfelt, romantic`,
  },
  {
    id: 'gufeng',
    category: 'world',
    title: '古风 / Gufeng',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Gufeng, ancient Chinese style, guzheng, bamboo flute, pipa, pentatonic melody, poetic, ethereal female vocals, traditional Chinese aesthetic`,
  },
  {
    id: 'afrobeat',
    category: 'world',
    title: 'Afrobeat',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Afrobeat, driving percussion, funky bass, horn section, groove, 120 BPM, West African rhythms, energetic`,
  },
  {
    id: 'latin-salsa',
    category: 'world',
    title: 'Latin / Salsa',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Salsa, Latin percussion, brass, 100 BPM, energetic, danceable, traditional Cuban style`,
  },
  {
    id: 'reggaeton',
    category: 'world',
    title: 'Reggaeton',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Reggaeton, dembow rhythm, 808 bass, Latin beat, 95 BPM, danceable, modern production, catchy hook`,
  },
  {
    id: 'celtic-irish',
    category: 'world',
    title: 'Celtic / Irish（凯尔特 / 爱尔兰）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Celtic folk, fiddle, tin whistle, bodhran drum, lively jig, 130 BPM, Irish traditional, acoustic`,
  },
  {
    id: 'middle-eastern',
    category: 'world',
    title: 'Middle Eastern（中东）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Middle Eastern, oud, darbuka percussion, quarter-tone melody, modal, 90 BPM, mystical, desert atmosphere`,
  },
  {
    id: 'indian-classical-fusion',
    category: 'world',
    title: 'Indian Classical（印度古典融合）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Indian classical fusion, sitar, tabla, tanpura drone, raga-based melody, meditative, 80 BPM, spiritual`,
  },

  // Hip-Hop
  {
    id: 'trap',
    category: 'hip-hop',
    title: 'Trap',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Trap, 808 drums, hi-hats, heavy bass, dark mood, 140 BPM, auto-tune vocals, hard-hitting`,
  },
  {
    id: 'boom-bap',
    category: 'hip-hop',
    title: 'Boom Bap（老学院）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Boom bap, classic hip-hop, sample-based, 90 BPM, raw, punchy drums, old school`,
  },
  {
    id: 'conscious-hip-hop',
    category: 'hip-hop',
    title: 'Conscious Hip-Hop（意识说唱）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Conscious hip-hop, lyrical, jazz samples, live drums, 90 BPM, thoughtful, warm bass, spoken word influence`,
  },
  {
    id: 'drill',
    category: 'hip-hop',
    title: 'Drill',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Drill, dark 808s, sliding bass, aggressive hi-hats, 140 BPM, minor key, ominous, menacing atmosphere`,
  },

  // Folk & Country
  {
    id: 'folk',
    category: 'folk-country',
    title: 'Folk（民谣）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Folk, acoustic guitar, harmonica, warm vocals, fingerpicking, storytelling, 100 BPM, earthy, intimate`,
  },
  {
    id: 'indie-folk',
    category: 'folk-country',
    title: 'Indie Folk（独立民谣）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Indie folk, acoustic guitar, banjo, soft harmonies, warm, campfire vibes, 95 BPM, gentle, introspective`,
  },
  {
    id: 'country',
    category: 'folk-country',
    title: 'Country（乡村）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Country, twangy electric guitar, steel guitar, fiddle, storytelling vocals, 110 BPM, Nashville sound, heartfelt`,
  },
  {
    id: 'bluegrass',
    category: 'folk-country',
    title: 'Bluegrass',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Bluegrass, fast banjo picking, fiddle, mandolin, upright bass, 140 BPM, energetic, Appalachian`,
  },

  // Funk / Disco / Gospel
  {
    id: 'funk',
    category: 'funk-disco-gospel',
    title: 'Funk（放克）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Funk, slap bass, wah guitar, tight drums, horn stabs, 100 BPM, groovy, syncopated, dancefloor energy`,
  },
  {
    id: 'disco',
    category: 'funk-disco-gospel',
    title: 'Disco（迪斯科）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Disco, four-on-the-floor kick, string section, funky bass, 120 BPM, 70s glamour, euphoric, dance anthem`,
  },
  {
    id: 'gospel',
    category: 'funk-disco-gospel',
    title: 'Gospel',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Gospel, choir harmonies, organ, clapping, soulful lead vocal, uplifting, spiritual, call-and-response, powerful`,
  },

  // Reggae / Ska
  {
    id: 'reggae',
    category: 'reggae-ska',
    title: 'Reggae（雷鬼）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Reggae, offbeat guitar skanks, deep bass, one drop rhythm, 75 BPM, laid-back, warm, roots feel`,
  },
  {
    id: 'ska',
    category: 'reggae-ska',
    title: 'Ska（斯卡）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Ska, fast offbeat guitar, brass section, upbeat, 150 BPM, energetic, punchy, dance-friendly`,
  },
  {
    id: 'dub',
    category: 'reggae-ska',
    title: 'Dub',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Dub, heavy bass, echo and reverb effects, spacious, 70 BPM, psychedelic, reggae-influenced, atmospheric`,
  },

  // Chinese singer templates (Suno doesn't accept direct artist names)
  {
    id: 'jay-chou',
    category: 'chinese-singers',
    title: '周杰伦',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `C-pop, piano-driven, complex arrangement, Chinese orchestral elements, pentatonic melody, R&B groove, cinematic production`,
  },
  {
    id: 'lin-jun-jie',
    category: 'chinese-singers',
    title: '林俊杰',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Mandopop ballad, emotional piano, lush string arrangement, soulful male vocals, polished production, 80 BPM, heartfelt`,
  },
  {
    id: 'gem-deng',
    category: 'chinese-singers',
    title: '邓紫棋',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Pop rock, powerful female vocals, emotional, electric guitar, modern electronic production, dynamic contrast, anthemic chorus`,
  },
  {
    id: 'li-ronghao',
    category: 'chinese-singers',
    title: '李荣浩',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Retro pop, vintage R&B, warm male vocals, analog production, funk-influenced groove, nostalgic, 1970s feel`,
  },
  {
    id: 'eason-chan',
    category: 'chinese-singers',
    title: '陈奕迅',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Cantopop ballad, soulful male vocals, emotional storytelling, layered arrangement, warm and melancholic, cinematic strings, 75 BPM`,
  },
  {
    id: 'wang-fei',
    category: 'chinese-singers',
    title: '王菲',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Dreamy pop, ethereal female vocals, trip-hop influence, alternative, reverb-heavy, atmospheric, introspective, 90s aesthetic`,
  },
];

export const sunoSourcePage = 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg';

