// Curated Unsplash CDN images — every style gets its own visual reference.
const SUNO_STYLE_IMAGES = {
  pop: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80&auto=format&fit=crop',
  'indie-pop': 'https://images.unsplash.com/photo-1517230878791-4d28214057c2?w=800&q=80&auto=format&fit=crop',
  'k-pop': 'https://images.unsplash.com/photo-1537365587684-f490102e1225?w=800&q=80&auto=format&fit=crop',
  'j-pop': 'https://images.unsplash.com/photo-1556856425-366d6618905d?w=800&q=80&auto=format&fit=crop',
  'synth-pop': 'https://images.unsplash.com/photo-1642177192159-f76c78e07690?w=800&q=80&auto=format&fit=crop',
  'bedroom-pop': 'https://images.unsplash.com/photo-1593697972672-b1c1902219e4?w=800&q=80&auto=format&fit=crop',
  rnb: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80&auto=format&fit=crop',
  'neo-soul': 'https://images.unsplash.com/photo-1588532218970-c2cab983746a?w=800&q=80&auto=format&fit=crop',
  'contemporary-rnb': 'https://images.unsplash.com/photo-1785594618400-eb7dbe7d881e?w=800&q=80&auto=format&fit=crop',
  'classic-rock': 'https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?w=800&q=80&auto=format&fit=crop',
  'indie-rock': 'https://images.unsplash.com/photo-1600779547877-be592ef5aad3?w=800&q=80&auto=format&fit=crop',
  metal: 'https://images.unsplash.com/photo-1565035010268-a3816f98589a?w=800&q=80&auto=format&fit=crop',
  'punk-rock': 'https://images.unsplash.com/photo-1503528108408-87b0d1c2b785?w=800&q=80&auto=format&fit=crop',
  grunge: 'https://images.unsplash.com/photo-1516924962500-2b4b3b99ea02?w=800&q=80&auto=format&fit=crop',
  'post-rock': 'https://images.unsplash.com/photo-1514649923863-ceaf75b7ec00?w=800&q=80&auto=format&fit=crop',
  shoegaze: 'https://images.unsplash.com/photo-1495228203641-7a107f6de4d6?w=800&q=80&auto=format&fit=crop',
  'lo-fi': 'https://images.unsplash.com/photo-1691697590646-c9b7bf6bef85?w=800&q=80&auto=format&fit=crop',
  'edm-house': 'https://images.unsplash.com/photo-1582711012124-a56cf82307a0?w=800&q=80&auto=format&fit=crop',
  'deep-house': 'https://images.unsplash.com/photo-1758267928164-20d7e74db707?w=800&q=80&auto=format&fit=crop',
  techno: 'https://images.unsplash.com/photo-1682068789645-c90caf6b32fa?w=800&q=80&auto=format&fit=crop',
  ambient: 'https://images.unsplash.com/photo-1548362851-ea052637ad64?w=800&q=80&auto=format&fit=crop',
  'drum-and-bass': 'https://images.unsplash.com/photo-1594623930572-300a3011d9ae?w=800&q=80&auto=format&fit=crop',
  'synthwave-retrowave': 'https://images.unsplash.com/photo-1706466615917-e44750d177d7?w=800&q=80&auto=format&fit=crop',
  chillwave: 'https://images.unsplash.com/photo-1503803548695-c2a7b4a5b875?w=800&q=80&auto=format&fit=crop',
  'smooth-jazz': 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80&auto=format&fit=crop',
  bebop: 'https://images.unsplash.com/photo-1541804627596-3b5b9ef58c93?w=800&q=80&auto=format&fit=crop',
  'bossa-nova': 'https://images.unsplash.com/photo-1785780224501-d5befd3e019c?w=800&q=80&auto=format&fit=crop',
  'jazz-fusion': 'https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=800&q=80&auto=format&fit=crop',
  'piano-solo': 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&q=80&auto=format&fit=crop',
  'chamber-music': 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&q=80&auto=format&fit=crop',
  'cinematic-film-score': 'https://images.unsplash.com/photo-1488630228244-bcdf33562a43?w=800&q=80&auto=format&fit=crop',
  neoclassical: 'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=800&q=80&auto=format&fit=crop',
  'chinese-traditional': 'https://images.unsplash.com/photo-1762006211581-3c705aba617b?w=800&q=80&auto=format&fit=crop',
  'chinese-orchestral': 'https://images.unsplash.com/photo-1551696785-927d4ac2d35b?w=800&q=80&auto=format&fit=crop',
  'chinese-pop': 'https://images.unsplash.com/photo-1600119692885-8b04faa7f329?w=800&q=80&auto=format&fit=crop',
  gufeng: 'https://images.unsplash.com/photo-1603384446936-5646a2481a36?w=800&q=80&auto=format&fit=crop',
  afrobeat: 'https://images.unsplash.com/photo-1605302596032-15e67c3cf66a?w=800&q=80&auto=format&fit=crop',
  'latin-salsa': 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800&q=80&auto=format&fit=crop',
  reggaeton: 'https://images.unsplash.com/photo-1581417478175-a9ef18f210c2?w=800&q=80&auto=format&fit=crop',
  'celtic-irish': 'https://images.unsplash.com/photo-1566805073441-d4a4b422bd96?w=800&q=80&auto=format&fit=crop',
  'middle-eastern': 'https://images.unsplash.com/photo-1764872566350-9452aef1f307?w=800&q=80&auto=format&fit=crop',
  'indian-classical-fusion': 'https://images.unsplash.com/photo-1703424943973-aabdc5d63e00?w=800&q=80&auto=format&fit=crop',
  trap: 'https://images.unsplash.com/photo-1682534434080-404a5edda2f3?w=800&q=80&auto=format&fit=crop',
  'boom-bap': 'https://images.unsplash.com/photo-1616681255209-368a2cd3e643?w=800&q=80&auto=format&fit=crop',
  'conscious-hip-hop': 'https://images.unsplash.com/photo-1485579149621-3123dd979885?w=800&q=80&auto=format&fit=crop',
  drill: 'https://images.unsplash.com/photo-1547079431-dd85cb27eda9?w=800&q=80&auto=format&fit=crop',
  folk: 'https://images.unsplash.com/photo-1524650359799-842906ca1c06?w=800&q=80&auto=format&fit=crop',
  'indie-folk': 'https://images.unsplash.com/photo-1609979100247-9ce6d45b386b?w=800&q=80&auto=format&fit=crop',
  country: 'https://images.unsplash.com/photo-1479708393961-bbdb87fd2514?w=800&q=80&auto=format&fit=crop',
  bluegrass: 'https://images.unsplash.com/photo-1568903457385-c38d34ffd37e?w=800&q=80&auto=format&fit=crop',
  funk: 'https://images.unsplash.com/photo-1445375011782-2384686778a0?w=800&q=80&auto=format&fit=crop',
  disco: 'https://images.unsplash.com/photo-1560987617-6de57e3d0574?w=800&q=80&auto=format&fit=crop',
  gospel: 'https://images.unsplash.com/photo-1519937754318-2462db1c429d?w=800&q=80&auto=format&fit=crop',
  reggae: 'https://images.unsplash.com/photo-1648090268311-4f1831fc5600?w=800&q=80&auto=format&fit=crop',
  ska: 'https://images.unsplash.com/photo-1598387181032-a3103a2db5b3?w=800&q=80&auto=format&fit=crop',
  dub: 'https://images.unsplash.com/photo-1573339887874-de759041d685?w=800&q=80&auto=format&fit=crop',
  'jay-chou': 'https://images.unsplash.com/photo-1552570173-43e2d76c37f4?w=800&q=80&auto=format&fit=crop',
  'lin-jun-jie': 'https://images.unsplash.com/photo-1595422656857-ced3a4a0ce25?w=800&q=80&auto=format&fit=crop',
  'gem-deng': 'https://images.unsplash.com/photo-1608319917470-9d9179430f8d?w=800&q=80&auto=format&fit=crop',
  'li-ronghao': 'https://images.unsplash.com/photo-1595971294624-80bcf0d7eb24?w=800&q=80&auto=format&fit=crop',
  'eason-chan': 'https://images.unsplash.com/photo-1521424159246-e4a66f267e4b?w=800&q=80&auto=format&fit=crop',
  'wang-fei': 'https://images.unsplash.com/photo-1637961239771-6578d3eb8d8e?w=800&q=80&auto=format&fit=crop',
};

export const sunoPrompts = [
  // Pop
  {
    id: 'pop',
    category: 'pop',
    title: 'Pop（流行）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Upbeat pop, catchy melody, synth pop, 120 BPM, Key of C major, radio-friendly, modern production, harmonic chorus`,
  },
  {
    id: 'indie-pop',
    category: 'pop',
    title: 'Indie Pop（独立流行）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Indie pop, dreamy synths, jangly guitar, soft vocals, 105 BPM, intimate production, bittersweet, warm`,
  },
  {
    id: 'k-pop',
    category: 'pop',
    title: 'K-Pop',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `K-pop, girl group, electronic, auto-tune vocals, dance beat, bright synth, 130 BPM, Korean lyrics`,
  },
  {
    id: 'j-pop',
    category: 'pop',
    title: 'J-Pop',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `J-pop, anime style, upbeat, piano-driven, cheerful, Japanese lyrics, catchy chorus`,
  },
  {
    id: 'synth-pop',
    category: 'pop',
    title: 'Synth Pop（合成器流行）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Synth pop, 80s inspired, analog synths, drum machine, bright melody, 118 BPM, retro-futuristic, polished`,
  },
  {
    id: 'bedroom-pop',
    category: 'pop',
    title: 'Bedroom Pop（卧室流行）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Bedroom pop, lo-fi production, soft vocals, guitar and synth, 100 BPM, hazy, personal, intimate recording`,
  },

  // R&B / Soul
  {
    id: 'rnb',
    category: 'rnb-soul',
    title: 'R&B（R&B / Soul）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Smooth R&B, slow groove, 85 BPM, Key of E minor, soulful vocals, piano, warm bass, bedroom vibes`,
  },
  {
    id: 'neo-soul',
    category: 'rnb-soul',
    title: 'Neo-Soul（新灵魂乐）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Neo-soul, laid-back, jazzy chords, 90 BPM, Key of G major, organic instrumentation, soulful, vintage feel`,
  },
  {
    id: 'contemporary-rnb',
    category: 'rnb-soul',
    title: 'Contemporary R&B（当代 R&B）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Contemporary R&B, atmospheric, 808 bass, ambient pads, falsetto vocals, 78 BPM, moody, dark production`,
  },

  // Rock
  {
    id: 'classic-rock',
    category: 'rock',
    title: 'Classic Rock（经典摇滚）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Classic rock, electric guitar, driving drums, 120 BPM, Key of A major, raw energy, anthemic chorus`,
  },
  {
    id: 'indie-rock',
    category: 'rock',
    title: 'Indie Rock（独立摇滚）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Indie rock, jangly guitar, earnest vocals, 110 BPM, dreamy, reverb-heavy, alternative`,
  },
  {
    id: 'metal',
    category: 'rock',
    title: 'Metal（金属）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Heavy metal, distorted guitars, double bass drums, aggressive, 180 BPM, dark, Key of D minor`,
  },
  {
    id: 'punk-rock',
    category: 'rock',
    title: 'Punk Rock（朋克摇滚）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Punk rock, fast tempo, distorted guitar, raw vocals, 160 BPM, rebellious, stripped-down production, energetic`,
  },
  {
    id: 'grunge',
    category: 'rock',
    title: 'Grunge（垃圾摇滚）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Grunge, heavy distorted guitar, angsty vocals, 110 BPM, 90s Seattle sound, raw, dynamic soft-loud contrast`,
  },
  {
    id: 'post-rock',
    category: 'rock',
    title: 'Post-Rock（后摇）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Post-rock, atmospheric guitar layers, crescendo builds, no vocals, instrumental, reverb-heavy, cinematic, 90 BPM`,
  },
  {
    id: 'shoegaze',
    category: 'rock',
    title: 'Shoegaze（自赏派）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Shoegaze, wall of distorted guitar, dreamy buried vocals, heavy reverb, ethereal, 95 BPM, hazy, layered textures`,
  },

  // Electronic
  {
    id: 'lo-fi',
    category: 'electronic',
    title: 'Lo-fi（慵懒电子）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Lo-fi hip hop, chill beats, vinyl crackle, 80 BPM, dusty samples, piano, relaxed`,
  },
  {
    id: 'edm-house',
    category: 'electronic',
    title: 'EDM / House',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `EDM, big room house, drop, festival anthem, four-on-the-floor beat, 128 BPM, euphoric, build-up`,
  },
  {
    id: 'deep-house',
    category: 'electronic',
    title: 'Deep House',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Deep house, groovy bassline, warm pads, 122 BPM, late-night atmosphere, smooth, subtle vocals, hypnotic`,
  },
  {
    id: 'techno',
    category: 'electronic',
    title: 'Techno',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Techno, driving beat, dark atmosphere, 130 BPM, industrial, hypnotic loops, minimal, underground club`,
  },
  {
    id: 'ambient',
    category: 'electronic',
    title: 'Ambient（氛围）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Ambient electronic, atmospheric, spacious, 60 BPM, synth pads, slowly evolving, meditative`,
  },
  {
    id: 'drum-and-bass',
    category: 'electronic',
    title: 'Drum & Bass',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Drum and bass, fast breakbeats, heavy sub-bass, 174 BPM, energetic, rolling drums, dark atmosphere`,
  },
  {
    id: 'synthwave-retrowave',
    category: 'electronic',
    title: 'Synthwave / Retrowave',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Synthwave, 80s retro electronic, neon atmosphere, pulsing bass, arpeggiated synths, 110 BPM, cinematic`,
  },
  {
    id: 'chillwave',
    category: 'electronic',
    title: 'Chillwave',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Chillwave, hazy synths, lo-fi texture, dreamy vocals, nostalgic, sun-drenched, 95 BPM, washed out`,
  },

  // Jazz
  {
    id: 'smooth-jazz',
    category: 'jazz',
    title: 'Smooth Jazz',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Smooth jazz, mellow saxophone, electric piano, soft drums, easy listening, warm, relaxed, wine bar atmosphere`,
  },
  {
    id: 'bebop',
    category: 'jazz',
    title: 'Bebop',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Bebop jazz, fast tempo, complex chord changes, saxophone lead, walking bass, ride cymbal, 1940s style, virtuosic`,
  },
  {
    id: 'bossa-nova',
    category: 'jazz',
    title: 'Bossa Nova',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Bossa nova, nylon guitar, soft percussion, gentle vocals, Brazilian jazz, 120 BPM, warm, romantic, laid-back`,
  },
  {
    id: 'jazz-fusion',
    category: 'jazz',
    title: 'Jazz Fusion（爵士融合）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Jazz fusion, electric instruments, rock energy, complex arrangements, 70s sophistication, funky, syncopated, 130 BPM`,
  },

  // Classical
  {
    id: 'piano-solo',
    category: 'classical',
    title: 'Piano Solo（钢琴独奏）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Piano solo, classical influence, romantic era, adagio tempo, emotional, expressive, Key of F minor`,
  },
  {
    id: 'chamber-music',
    category: 'classical',
    title: 'Chamber Music（室内乐）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Chamber ensemble, string quartet, elegant, Baroque style, delicate, intricate harmonies`,
  },
  {
    id: 'cinematic-film-score',
    category: 'classical',
    title: 'Cinematic / Film Score（影视配乐）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Cinematic orchestral, epic strings, brass fanfare, timpani, heroic, sweeping melody, film soundtrack, grand`,
  },
  {
    id: 'neoclassical',
    category: 'classical',
    title: 'Neoclassical（新古典）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Neoclassical, modern classical, piano and strings, minimal, emotional, Nils Frahm style, contemplative, spacious`,
  },

  // World Music
  {
    id: 'chinese-traditional',
    category: 'world',
    title: 'Chinese Traditional（中国传统）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Chinese traditional, guzheng, bamboo flute (dizi), peaceful, nature sounds, classical Chinese mood`,
  },
  {
    id: 'chinese-orchestral',
    category: 'world',
    title: 'Chinese Orchestral（国风交响）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Chinese orchestral, erhu melody, pipa arpeggios, guzheng, pentatonic scale, grand, emotional, traditional Chinese instruments with orchestral strings`,
  },
  {
    id: 'chinese-pop',
    category: 'world',
    title: 'Chinese Pop / 华语流行',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `C-pop ballad, emotional piano, string section, Mandarin lyrics, tender vocals, 75 BPM, heartfelt, romantic`,
  },
  {
    id: 'gufeng',
    category: 'world',
    title: '古风 / Gufeng',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Gufeng, ancient Chinese style, guzheng, bamboo flute, pipa, pentatonic melody, poetic, ethereal female vocals, traditional Chinese aesthetic`,
  },
  {
    id: 'afrobeat',
    category: 'world',
    title: 'Afrobeat',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Afrobeat, driving percussion, funky bass, horn section, groove, 120 BPM, West African rhythms, energetic`,
  },
  {
    id: 'latin-salsa',
    category: 'world',
    title: 'Latin / Salsa',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Salsa, Latin percussion, brass, 100 BPM, energetic, danceable, traditional Cuban style`,
  },
  {
    id: 'reggaeton',
    category: 'world',
    title: 'Reggaeton',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Reggaeton, dembow rhythm, 808 bass, Latin beat, 95 BPM, danceable, modern production, catchy hook`,
  },
  {
    id: 'celtic-irish',
    category: 'world',
    title: 'Celtic / Irish（凯尔特 / 爱尔兰）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Celtic folk, fiddle, tin whistle, bodhran drum, lively jig, 130 BPM, Irish traditional, acoustic`,
  },
  {
    id: 'middle-eastern',
    category: 'world',
    title: 'Middle Eastern（中东）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Middle Eastern, oud, darbuka percussion, quarter-tone melody, modal, 90 BPM, mystical, desert atmosphere`,
  },
  {
    id: 'indian-classical-fusion',
    category: 'world',
    title: 'Indian Classical（印度古典融合）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Indian classical fusion, sitar, tabla, tanpura drone, raga-based melody, meditative, 80 BPM, spiritual`,
  },

  // Hip-Hop
  {
    id: 'trap',
    category: 'hip-hop',
    title: 'Trap',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Trap, 808 drums, hi-hats, heavy bass, dark mood, 140 BPM, auto-tune vocals, hard-hitting`,
  },
  {
    id: 'boom-bap',
    category: 'hip-hop',
    title: 'Boom Bap（老学院）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Boom bap, classic hip-hop, sample-based, 90 BPM, raw, punchy drums, old school`,
  },
  {
    id: 'conscious-hip-hop',
    category: 'hip-hop',
    title: 'Conscious Hip-Hop（意识说唱）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Conscious hip-hop, lyrical, jazz samples, live drums, 90 BPM, thoughtful, warm bass, spoken word influence`,
  },
  {
    id: 'drill',
    category: 'hip-hop',
    title: 'Drill',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Drill, dark 808s, sliding bass, aggressive hi-hats, 140 BPM, minor key, ominous, menacing atmosphere`,
  },

  // Folk & Country
  {
    id: 'folk',
    category: 'folk-country',
    title: 'Folk（民谣）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Folk, acoustic guitar, harmonica, warm vocals, fingerpicking, storytelling, 100 BPM, earthy, intimate`,
  },
  {
    id: 'indie-folk',
    category: 'folk-country',
    title: 'Indie Folk（独立民谣）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Indie folk, acoustic guitar, banjo, soft harmonies, warm, campfire vibes, 95 BPM, gentle, introspective`,
  },
  {
    id: 'country',
    category: 'folk-country',
    title: 'Country（乡村）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Country, twangy electric guitar, steel guitar, fiddle, storytelling vocals, 110 BPM, Nashville sound, heartfelt`,
  },
  {
    id: 'bluegrass',
    category: 'folk-country',
    title: 'Bluegrass',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Bluegrass, fast banjo picking, fiddle, mandolin, upright bass, 140 BPM, energetic, Appalachian`,
  },

  // Funk / Disco / Gospel
  {
    id: 'funk',
    category: 'funk-disco-gospel',
    title: 'Funk（放克）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Funk, slap bass, wah guitar, tight drums, horn stabs, 100 BPM, groovy, syncopated, dancefloor energy`,
  },
  {
    id: 'disco',
    category: 'funk-disco-gospel',
    title: 'Disco（迪斯科）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Disco, four-on-the-floor kick, string section, funky bass, 120 BPM, 70s glamour, euphoric, dance anthem`,
  },
  {
    id: 'gospel',
    category: 'funk-disco-gospel',
    title: 'Gospel',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Gospel, choir harmonies, organ, clapping, soulful lead vocal, uplifting, spiritual, call-and-response, powerful`,
  },

  // Reggae / Ska
  {
    id: 'reggae',
    category: 'reggae-ska',
    title: 'Reggae（雷鬼）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Reggae, offbeat guitar skanks, deep bass, one drop rhythm, 75 BPM, laid-back, warm, roots feel`,
  },
  {
    id: 'ska',
    category: 'reggae-ska',
    title: 'Ska（斯卡）',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Ska, fast offbeat guitar, brass section, upbeat, 150 BPM, energetic, punchy, dance-friendly`,
  },
  {
    id: 'dub',
    category: 'reggae-ska',
    title: 'Dub',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Dub, heavy bass, echo and reverb effects, spacious, 70 BPM, psychedelic, reggae-influenced, atmospheric`,
  },

  // Chinese singer templates (Suno doesn't accept direct artist names)
  {
    id: 'jay-chou',
    category: 'chinese-singers',
    title: '周杰伦',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `C-pop, piano-driven, complex arrangement, Chinese orchestral elements, pentatonic melody, R&B groove, cinematic production`,
  },
  {
    id: 'lin-jun-jie',
    category: 'chinese-singers',
    title: '林俊杰',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Mandopop ballad, emotional piano, lush string arrangement, soulful male vocals, polished production, 80 BPM, heartfelt`,
  },
  {
    id: 'gem-deng',
    category: 'chinese-singers',
    title: '邓紫棋',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Pop rock, powerful female vocals, emotional, electric guitar, modern electronic production, dynamic contrast, anthemic chorus`,
  },
  {
    id: 'li-ronghao',
    category: 'chinese-singers',
    title: '李荣浩',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Retro pop, vintage R&B, warm male vocals, analog production, funk-influenced groove, nostalgic, 1970s feel`,
  },
  {
    id: 'eason-chan',
    category: 'chinese-singers',
    title: '陈奕迅',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Cantopop ballad, soulful male vocals, emotional storytelling, layered arrangement, warm and melancholic, cinematic strings, 75 BPM`,
  },
  {
    id: 'wang-fei',
    category: 'chinese-singers',
    title: '王菲',
    image: '/main-page.png',
    source: 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg',
    prompt: `Dreamy pop, ethereal female vocals, trip-hop influence, alternative, reverb-heavy, atmospheric, introspective, 90s aesthetic`,
  },
].map((prompt) => ({
  ...prompt,
  image: SUNO_STYLE_IMAGES[prompt.id],
}));

export const sunoSourcePage = 'https://mp.weixin.qq.com/s/XivGB3kv0xECXOEaCGxkBg';
